/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TomskRouteImport } from './routes/tomsk'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as SvedenRouteImport } from './routes/sveden'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RaspisanieRouteImport } from './routes/raspisanie'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LkRouteImport } from './routes/lk'
import { Route as KrasnoyarskRouteImport } from './routes/krasnoyarsk'
import { Route as KemerovoRouteImport } from './routes/kemerovo'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as CorpCalcRouteImport } from './routes/corp-calc'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OtrasliIndexRouteImport } from './routes/otrasli.index'
import { Route as NapravleniyaIndexRouteImport } from './routes/napravleniya.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as OtrasliSlugRouteImport } from './routes/otrasli.$slug'
import { Route as NapravleniyaSlugRouteImport } from './routes/napravleniya.$slug'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminTeachersRouteImport } from './routes/_authenticated/admin.teachers'
import { Route as AuthenticatedAdminSiteScheduleRouteImport } from './routes/_authenticated/admin.site-schedule'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminSchedulesRouteImport } from './routes/_authenticated/admin.schedules'
import { Route as AuthenticatedAdminReviewsRouteImport } from './routes/_authenticated/admin.reviews'
import { Route as AuthenticatedAdminPromocodesRouteImport } from './routes/_authenticated/admin.promocodes'
import { Route as AuthenticatedAdminGalleryRouteImport } from './routes/_authenticated/admin.gallery'
import { Route as AuthenticatedAdminDocumentsRouteImport } from './routes/_authenticated/admin.documents'
import { Route as AuthenticatedAdminDocSamplesRouteImport } from './routes/_authenticated/admin.doc-samples'
import { Route as AuthenticatedAdminCertificatesRouteImport } from './routes/_authenticated/admin.certificates'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminBannersRouteImport } from './routes/_authenticated/admin.banners'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminApplicationsRouteImport } from './routes/_authenticated/admin.applications'
import { Route as AuthenticatedAdminCoursesIndexRouteImport } from './routes/_authenticated/admin.courses.index'
import { Route as AuthenticatedAdminBlogIndexRouteImport } from './routes/_authenticated/admin.blog.index'
import { Route as AuthenticatedAdminCoursesIdRouteImport } from './routes/_authenticated/admin.courses.$id'
import { Route as AuthenticatedAdminBlogIdRouteImport } from './routes/_authenticated/admin.blog.$id'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TomskRoute = TomskRouteImport.update({
  id: '/tomsk',
  path: '/tomsk',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const SvedenRoute = SvedenRouteImport.update({
  id: '/sveden',
  path: '/sveden',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RaspisanieRoute = RaspisanieRouteImport.update({
  id: '/raspisanie',
  path: '/raspisanie',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LkRoute = LkRouteImport.update({
  id: '/lk',
  path: '/lk',
  getParentRoute: () => rootRouteImport,
} as any)
const KrasnoyarskRoute = KrasnoyarskRouteImport.update({
  id: '/krasnoyarsk',
  path: '/krasnoyarsk',
  getParentRoute: () => rootRouteImport,
} as any)
const KemerovoRoute = KemerovoRouteImport.update({
  id: '/kemerovo',
  path: '/kemerovo',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CorpCalcRoute = CorpCalcRouteImport.update({
  id: '/corp-calc',
  path: '/corp-calc',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OtrasliIndexRoute = OtrasliIndexRouteImport.update({
  id: '/otrasli/',
  path: '/otrasli/',
  getParentRoute: () => rootRouteImport,
} as any)
const NapravleniyaIndexRoute = NapravleniyaIndexRouteImport.update({
  id: '/napravleniya/',
  path: '/napravleniya/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const OtrasliSlugRoute = OtrasliSlugRouteImport.update({
  id: '/otrasli/$slug',
  path: '/otrasli/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NapravleniyaSlugRoute = NapravleniyaSlugRouteImport.update({
  id: '/napravleniya/$slug',
  path: '/napravleniya/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTeachersRoute =
  AuthenticatedAdminTeachersRouteImport.update({
    id: '/teachers',
    path: '/teachers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSiteScheduleRoute =
  AuthenticatedAdminSiteScheduleRouteImport.update({
    id: '/site-schedule',
    path: '/site-schedule',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSchedulesRoute =
  AuthenticatedAdminSchedulesRouteImport.update({
    id: '/schedules',
    path: '/schedules',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReviewsRoute =
  AuthenticatedAdminReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPromocodesRoute =
  AuthenticatedAdminPromocodesRouteImport.update({
    id: '/promocodes',
    path: '/promocodes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGalleryRoute =
  AuthenticatedAdminGalleryRouteImport.update({
    id: '/gallery',
    path: '/gallery',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDocumentsRoute =
  AuthenticatedAdminDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDocSamplesRoute =
  AuthenticatedAdminDocSamplesRouteImport.update({
    id: '/doc-samples',
    path: '/doc-samples',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCertificatesRoute =
  AuthenticatedAdminCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBannersRoute =
  AuthenticatedAdminBannersRouteImport.update({
    id: '/banners',
    path: '/banners',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminApplicationsRoute =
  AuthenticatedAdminApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCoursesIndexRoute =
  AuthenticatedAdminCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogIndexRoute =
  AuthenticatedAdminBlogIndexRouteImport.update({
    id: '/blog/',
    path: '/blog/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCoursesIdRoute =
  AuthenticatedAdminCoursesIdRouteImport.update({
    id: '/courses/$id',
    path: '/courses/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogIdRoute =
  AuthenticatedAdminBlogIdRouteImport.update({
    id: '/blog/$id',
    path: '/blog/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/contacts': typeof ContactsRoute
  '/corp-calc': typeof CorpCalcRoute
  '/gallery': typeof GalleryRoute
  '/kemerovo': typeof KemerovoRoute
  '/krasnoyarsk': typeof KrasnoyarskRoute
  '/lk': typeof LkRoute
  '/privacy': typeof PrivacyRoute
  '/raspisanie': typeof RaspisanieRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sveden': typeof SvedenRoute
  '/teachers': typeof TeachersRoute
  '/tomsk': typeof TomskRoute
  '/verify': typeof VerifyRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/napravleniya/$slug': typeof NapravleniyaSlugRoute
  '/otrasli/$slug': typeof OtrasliSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/napravleniya/': typeof NapravleniyaIndexRoute
  '/otrasli/': typeof OtrasliIndexRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/admin/doc-samples': typeof AuthenticatedAdminDocSamplesRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/promocodes': typeof AuthenticatedAdminPromocodesRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/schedules': typeof AuthenticatedAdminSchedulesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/site-schedule': typeof AuthenticatedAdminSiteScheduleRoute
  '/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/admin/courses/$id': typeof AuthenticatedAdminCoursesIdRoute
  '/admin/blog/': typeof AuthenticatedAdminBlogIndexRoute
  '/admin/courses/': typeof AuthenticatedAdminCoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/contacts': typeof ContactsRoute
  '/corp-calc': typeof CorpCalcRoute
  '/gallery': typeof GalleryRoute
  '/kemerovo': typeof KemerovoRoute
  '/krasnoyarsk': typeof KrasnoyarskRoute
  '/lk': typeof LkRoute
  '/privacy': typeof PrivacyRoute
  '/raspisanie': typeof RaspisanieRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sveden': typeof SvedenRoute
  '/teachers': typeof TeachersRoute
  '/tomsk': typeof TomskRoute
  '/verify': typeof VerifyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/napravleniya/$slug': typeof NapravleniyaSlugRoute
  '/otrasli/$slug': typeof OtrasliSlugRoute
  '/blog': typeof BlogIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/napravleniya': typeof NapravleniyaIndexRoute
  '/otrasli': typeof OtrasliIndexRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/admin/doc-samples': typeof AuthenticatedAdminDocSamplesRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/promocodes': typeof AuthenticatedAdminPromocodesRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/schedules': typeof AuthenticatedAdminSchedulesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/site-schedule': typeof AuthenticatedAdminSiteScheduleRoute
  '/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/admin/courses/$id': typeof AuthenticatedAdminCoursesIdRoute
  '/admin/blog': typeof AuthenticatedAdminBlogIndexRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/contacts': typeof ContactsRoute
  '/corp-calc': typeof CorpCalcRoute
  '/gallery': typeof GalleryRoute
  '/kemerovo': typeof KemerovoRoute
  '/krasnoyarsk': typeof KrasnoyarskRoute
  '/lk': typeof LkRoute
  '/privacy': typeof PrivacyRoute
  '/raspisanie': typeof RaspisanieRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sveden': typeof SvedenRoute
  '/teachers': typeof TeachersRoute
  '/tomsk': typeof TomskRoute
  '/verify': typeof VerifyRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/napravleniya/$slug': typeof NapravleniyaSlugRoute
  '/otrasli/$slug': typeof OtrasliSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/napravleniya/': typeof NapravleniyaIndexRoute
  '/otrasli/': typeof OtrasliIndexRoute
  '/_authenticated/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/_authenticated/admin/doc-samples': typeof AuthenticatedAdminDocSamplesRoute
  '/_authenticated/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/_authenticated/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/_authenticated/admin/promocodes': typeof AuthenticatedAdminPromocodesRoute
  '/_authenticated/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/_authenticated/admin/schedules': typeof AuthenticatedAdminSchedulesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/site-schedule': typeof AuthenticatedAdminSiteScheduleRoute
  '/_authenticated/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/_authenticated/admin/courses/$id': typeof AuthenticatedAdminCoursesIdRoute
  '/_authenticated/admin/blog/': typeof AuthenticatedAdminBlogIndexRoute
  '/_authenticated/admin/courses/': typeof AuthenticatedAdminCoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/compare'
    | '/contacts'
    | '/corp-calc'
    | '/gallery'
    | '/kemerovo'
    | '/krasnoyarsk'
    | '/lk'
    | '/privacy'
    | '/raspisanie'
    | '/sitemap.xml'
    | '/sveden'
    | '/teachers'
    | '/tomsk'
    | '/verify'
    | '/admin'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/napravleniya/$slug'
    | '/otrasli/$slug'
    | '/blog/'
    | '/courses/'
    | '/napravleniya/'
    | '/otrasli/'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/certificates'
    | '/admin/doc-samples'
    | '/admin/documents'
    | '/admin/gallery'
    | '/admin/promocodes'
    | '/admin/reviews'
    | '/admin/schedules'
    | '/admin/settings'
    | '/admin/site-schedule'
    | '/admin/teachers'
    | '/admin/'
    | '/admin/blog/$id'
    | '/admin/courses/$id'
    | '/admin/blog/'
    | '/admin/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/compare'
    | '/contacts'
    | '/corp-calc'
    | '/gallery'
    | '/kemerovo'
    | '/krasnoyarsk'
    | '/lk'
    | '/privacy'
    | '/raspisanie'
    | '/sitemap.xml'
    | '/sveden'
    | '/teachers'
    | '/tomsk'
    | '/verify'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/napravleniya/$slug'
    | '/otrasli/$slug'
    | '/blog'
    | '/courses'
    | '/napravleniya'
    | '/otrasli'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/certificates'
    | '/admin/doc-samples'
    | '/admin/documents'
    | '/admin/gallery'
    | '/admin/promocodes'
    | '/admin/reviews'
    | '/admin/schedules'
    | '/admin/settings'
    | '/admin/site-schedule'
    | '/admin/teachers'
    | '/admin'
    | '/admin/blog/$id'
    | '/admin/courses/$id'
    | '/admin/blog'
    | '/admin/courses'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/compare'
    | '/contacts'
    | '/corp-calc'
    | '/gallery'
    | '/kemerovo'
    | '/krasnoyarsk'
    | '/lk'
    | '/privacy'
    | '/raspisanie'
    | '/sitemap.xml'
    | '/sveden'
    | '/teachers'
    | '/tomsk'
    | '/verify'
    | '/_authenticated/admin'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/napravleniya/$slug'
    | '/otrasli/$slug'
    | '/blog/'
    | '/courses/'
    | '/napravleniya/'
    | '/otrasli/'
    | '/_authenticated/admin/applications'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/banners'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/certificates'
    | '/_authenticated/admin/doc-samples'
    | '/_authenticated/admin/documents'
    | '/_authenticated/admin/gallery'
    | '/_authenticated/admin/promocodes'
    | '/_authenticated/admin/reviews'
    | '/_authenticated/admin/schedules'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/site-schedule'
    | '/_authenticated/admin/teachers'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/blog/$id'
    | '/_authenticated/admin/courses/$id'
    | '/_authenticated/admin/blog/'
    | '/_authenticated/admin/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CompareRoute: typeof CompareRoute
  ContactsRoute: typeof ContactsRoute
  CorpCalcRoute: typeof CorpCalcRoute
  GalleryRoute: typeof GalleryRoute
  KemerovoRoute: typeof KemerovoRoute
  KrasnoyarskRoute: typeof KrasnoyarskRoute
  LkRoute: typeof LkRoute
  PrivacyRoute: typeof PrivacyRoute
  RaspisanieRoute: typeof RaspisanieRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SvedenRoute: typeof SvedenRoute
  TeachersRoute: typeof TeachersRoute
  TomskRoute: typeof TomskRoute
  VerifyRoute: typeof VerifyRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  NapravleniyaSlugRoute: typeof NapravleniyaSlugRoute
  OtrasliSlugRoute: typeof OtrasliSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  NapravleniyaIndexRoute: typeof NapravleniyaIndexRoute
  OtrasliIndexRoute: typeof OtrasliIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tomsk': {
      id: '/tomsk'
      path: '/tomsk'
      fullPath: '/tomsk'
      preLoaderRoute: typeof TomskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sveden': {
      id: '/sveden'
      path: '/sveden'
      fullPath: '/sveden'
      preLoaderRoute: typeof SvedenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raspisanie': {
      id: '/raspisanie'
      path: '/raspisanie'
      fullPath: '/raspisanie'
      preLoaderRoute: typeof RaspisanieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lk': {
      id: '/lk'
      path: '/lk'
      fullPath: '/lk'
      preLoaderRoute: typeof LkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/krasnoyarsk': {
      id: '/krasnoyarsk'
      path: '/krasnoyarsk'
      fullPath: '/krasnoyarsk'
      preLoaderRoute: typeof KrasnoyarskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kemerovo': {
      id: '/kemerovo'
      path: '/kemerovo'
      fullPath: '/kemerovo'
      preLoaderRoute: typeof KemerovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corp-calc': {
      id: '/corp-calc'
      path: '/corp-calc'
      fullPath: '/corp-calc'
      preLoaderRoute: typeof CorpCalcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otrasli/': {
      id: '/otrasli/'
      path: '/otrasli'
      fullPath: '/otrasli/'
      preLoaderRoute: typeof OtrasliIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/napravleniya/': {
      id: '/napravleniya/'
      path: '/napravleniya'
      fullPath: '/napravleniya/'
      preLoaderRoute: typeof NapravleniyaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otrasli/$slug': {
      id: '/otrasli/$slug'
      path: '/otrasli/$slug'
      fullPath: '/otrasli/$slug'
      preLoaderRoute: typeof OtrasliSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/napravleniya/$slug': {
      id: '/napravleniya/$slug'
      path: '/napravleniya/$slug'
      fullPath: '/napravleniya/$slug'
      preLoaderRoute: typeof NapravleniyaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/teachers': {
      id: '/_authenticated/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AuthenticatedAdminTeachersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/site-schedule': {
      id: '/_authenticated/admin/site-schedule'
      path: '/site-schedule'
      fullPath: '/admin/site-schedule'
      preLoaderRoute: typeof AuthenticatedAdminSiteScheduleRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/schedules': {
      id: '/_authenticated/admin/schedules'
      path: '/schedules'
      fullPath: '/admin/schedules'
      preLoaderRoute: typeof AuthenticatedAdminSchedulesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reviews': {
      id: '/_authenticated/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/promocodes': {
      id: '/_authenticated/admin/promocodes'
      path: '/promocodes'
      fullPath: '/admin/promocodes'
      preLoaderRoute: typeof AuthenticatedAdminPromocodesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/gallery': {
      id: '/_authenticated/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AuthenticatedAdminGalleryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/documents': {
      id: '/_authenticated/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AuthenticatedAdminDocumentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/doc-samples': {
      id: '/_authenticated/admin/doc-samples'
      path: '/doc-samples'
      fullPath: '/admin/doc-samples'
      preLoaderRoute: typeof AuthenticatedAdminDocSamplesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/certificates': {
      id: '/_authenticated/admin/certificates'
      path: '/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AuthenticatedAdminCertificatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/banners': {
      id: '/_authenticated/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AuthenticatedAdminBannersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/applications': {
      id: '/_authenticated/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AuthenticatedAdminApplicationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/courses/': {
      id: '/_authenticated/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AuthenticatedAdminCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog/': {
      id: '/_authenticated/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AuthenticatedAdminBlogIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/courses/$id': {
      id: '/_authenticated/admin/courses/$id'
      path: '/courses/$id'
      fullPath: '/admin/courses/$id'
      preLoaderRoute: typeof AuthenticatedAdminCoursesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog/$id': {
      id: '/_authenticated/admin/blog/$id'
      path: '/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AuthenticatedAdminBlogIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminApplicationsRoute: typeof AuthenticatedAdminApplicationsRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBannersRoute: typeof AuthenticatedAdminBannersRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminCertificatesRoute: typeof AuthenticatedAdminCertificatesRoute
  AuthenticatedAdminDocSamplesRoute: typeof AuthenticatedAdminDocSamplesRoute
  AuthenticatedAdminDocumentsRoute: typeof AuthenticatedAdminDocumentsRoute
  AuthenticatedAdminGalleryRoute: typeof AuthenticatedAdminGalleryRoute
  AuthenticatedAdminPromocodesRoute: typeof AuthenticatedAdminPromocodesRoute
  AuthenticatedAdminReviewsRoute: typeof AuthenticatedAdminReviewsRoute
  AuthenticatedAdminSchedulesRoute: typeof AuthenticatedAdminSchedulesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSiteScheduleRoute: typeof AuthenticatedAdminSiteScheduleRoute
  AuthenticatedAdminTeachersRoute: typeof AuthenticatedAdminTeachersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminBlogIdRoute: typeof AuthenticatedAdminBlogIdRoute
  AuthenticatedAdminCoursesIdRoute: typeof AuthenticatedAdminCoursesIdRoute
  AuthenticatedAdminBlogIndexRoute: typeof AuthenticatedAdminBlogIndexRoute
  AuthenticatedAdminCoursesIndexRoute: typeof AuthenticatedAdminCoursesIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminApplicationsRoute: AuthenticatedAdminApplicationsRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminBannersRoute: AuthenticatedAdminBannersRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminCertificatesRoute: AuthenticatedAdminCertificatesRoute,
  AuthenticatedAdminDocSamplesRoute: AuthenticatedAdminDocSamplesRoute,
  AuthenticatedAdminDocumentsRoute: AuthenticatedAdminDocumentsRoute,
  AuthenticatedAdminGalleryRoute: AuthenticatedAdminGalleryRoute,
  AuthenticatedAdminPromocodesRoute: AuthenticatedAdminPromocodesRoute,
  AuthenticatedAdminReviewsRoute: AuthenticatedAdminReviewsRoute,
  AuthenticatedAdminSchedulesRoute: AuthenticatedAdminSchedulesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSiteScheduleRoute: AuthenticatedAdminSiteScheduleRoute,
  AuthenticatedAdminTeachersRoute: AuthenticatedAdminTeachersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminBlogIdRoute: AuthenticatedAdminBlogIdRoute,
  AuthenticatedAdminCoursesIdRoute: AuthenticatedAdminCoursesIdRoute,
  AuthenticatedAdminBlogIndexRoute: AuthenticatedAdminBlogIndexRoute,
  AuthenticatedAdminCoursesIndexRoute: AuthenticatedAdminCoursesIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CompareRoute: CompareRoute,
  ContactsRoute: ContactsRoute,
  CorpCalcRoute: CorpCalcRoute,
  GalleryRoute: GalleryRoute,
  KemerovoRoute: KemerovoRoute,
  KrasnoyarskRoute: KrasnoyarskRoute,
  LkRoute: LkRoute,
  PrivacyRoute: PrivacyRoute,
  RaspisanieRoute: RaspisanieRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SvedenRoute: SvedenRoute,
  TeachersRoute: TeachersRoute,
  TomskRoute: TomskRoute,
  VerifyRoute: VerifyRoute,
  BlogSlugRoute: BlogSlugRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  NapravleniyaSlugRoute: NapravleniyaSlugRoute,
  OtrasliSlugRoute: OtrasliSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  NapravleniyaIndexRoute: NapravleniyaIndexRoute,
  OtrasliIndexRoute: OtrasliIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
